import {StyleSheet} from 'react-native';
import {colors, radius, space} from '../constants/theme';

export const styles = StyleSheet.create({
  card: {backgroundColor: colors.surface, borderRadius: radius.lg, padding: 14, marginBottom: space.md, borderWidth: 1, borderColor: colors.border},
  topRow: {flexDirection: 'row', gap: 12},
  imageContainer: {width: 100, height: 105, borderRadius: radius.md, overflow: 'hidden', position: 'relative', backgroundColor: colors.primarySoft},
  image: {width: '100%', height: '100%'},
  imagePlaceholder: {width: '100%', height: '100%', backgroundColor: '#E7F5EE', alignItems: 'center', justifyContent: 'center'},
  placeholderIcon: {fontSize: 38},
  favButton: {position: 'absolute', top: 5, right: 5, width: 26, height: 26, borderRadius: 13, backgroundColor: 'rgba(255, 255, 255, 0.9)', alignItems: 'center', justifyContent: 'center'},
  favIcon: {fontSize: 12},
  imageBadge: {position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(16, 40, 30, 0.85)', paddingVertical: 3, paddingHorizontal: 4},
  imageBadgeText: {color: '#FFFFFF', fontSize: 9, fontWeight: '700', textAlign: 'center'},
  bodyContainer: {flex: 1, justifyContent: 'space-between'},
  titleRow: {flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between'},
  titleTextWrap: {flex: 1, marginRight: 6},
  nameVerifiedRow: {flexDirection: 'row', alignItems: 'center', gap: 4},
  nameText: {fontSize: 16, fontWeight: '800', color: colors.text, flexShrink: 1},
  verifiedBadge: {width: 16, height: 16, borderRadius: 8, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center'},
  verifiedIcon: {color: '#FFFFFF', fontSize: 10, fontWeight: '900'},
  subTypeText: {fontSize: 12, fontWeight: '600', color: colors.textSoft, marginTop: 1},
  callButton: {width: 34, height: 34, borderRadius: 17, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center'},
  callIcon: {fontSize: 15},
  locationRow: {flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4},
  locIcon: {fontSize: 12},
  locationText: {fontSize: 12, fontWeight: '500', color: colors.textMuted, flex: 1},
  statusRow: {flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6, marginTop: 6},
  metaChip: {backgroundColor: colors.bg, paddingHorizontal: 7, paddingVertical: 3, borderRadius: radius.pill},
  metaChipText: {fontSize: 11, fontWeight: '600', color: colors.textSoft},
  statusChip: {flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 3, borderRadius: radius.pill, gap: 4},
  statusOpen: {backgroundColor: '#E7F5EE'},
  statusClosed: {backgroundColor: colors.dangerSoft},
  statusDot: {width: 6, height: 6, borderRadius: 3},
  dotOpen: {backgroundColor: colors.accent},
  dotClosed: {backgroundColor: colors.danger},
  statusText: {fontSize: 11, fontWeight: '700'},
  textOpen: {color: colors.primaryDark},
  textClosed: {color: colors.danger},
  closesText: {fontSize: 11, color: colors.textSoft, fontWeight: '500'},
  ratingRow: {flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4},
  starIcon: {fontSize: 13},
  ratingValue: {fontSize: 13, fontWeight: '700', color: colors.text},
  reviewsText: {fontSize: 12, color: colors.textSoft},
  tagsRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 6},
  tagChip: {backgroundColor: colors.primarySoft, paddingHorizontal: 7, paddingVertical: 3, borderRadius: radius.sm},
  tagText: {fontSize: 11, color: colors.primaryDark, fontWeight: '600'},
  actionsRow: {flexDirection: 'row', gap: 10, marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: '#F0F4F2'},
  detailsButton: {flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', minHeight: 40, borderRadius: radius.md, borderWidth: 1.5, borderColor: colors.border, backgroundColor: colors.surface, gap: 6},
  detailsIcon: {fontSize: 13, color: colors.primaryDark, fontWeight: '700'},
  detailsText: {fontSize: 13, fontWeight: '700', color: colors.primaryDark},
  directionsButton: {flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', minHeight: 40, borderRadius: radius.md, backgroundColor: colors.primaryDark, gap: 6},
  directionsIcon: {fontSize: 13, color: '#FFFFFF', fontWeight: '700'},
  directionsText: {fontSize: 13, fontWeight: '700', color: '#FFFFFF'},
});
