export const FACILITY_TYPES = {
  HOSPITAL: 'HOSPITAL',
  NURSING_HOME: 'NURSING_HOME',
  CLINIC: 'CLINIC',
  DIAGNOSTIC_CENTRE: 'DIAGNOSTIC_CENTRE',
  LABORATORY: 'LABORATORY',
  PHARMACY: 'PHARMACY',
  MEDICINE_SHOP: 'MEDICINE_SHOP',
};

export const TYPE_LABEL = {
  HOSPITAL: 'Hospital',
  NURSING_HOME: 'Nursing Home',
  CLINIC: 'Clinic',
  DIAGNOSTIC_CENTRE: 'Diagnostic Center',
  LABORATORY: 'Laboratory',
  PHARMACY: 'Pharmacy',
  MEDICINE_SHOP: 'Medicine Shop',
  DOCTOR: 'Doctor',
};

export const PHARMACY_TYPES = [FACILITY_TYPES.PHARMACY, FACILITY_TYPES.MEDICINE_SHOP];
